apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: harbor-minio
    component: minio
  name: harbor-minio
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 400Gi
  storageClassName: gp3
  volumeMode: Filesystem
