apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/redhat-et/coding_agent_bench
    newTag: stage

patches:
  - target:
      kind: Secret
      name: intake-poller-secret
    patch: |
      - op: replace
        path: /stringData/ENVIRONMENT
        value: stage
