[project]
name = "harbor-itbench-aa-adapter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Daniel Blei", email = "dblei@redhat.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pyyaml",
]

[project.scripts]
itbench-aa = "itbench_aa.main:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "itbench_aa"
