apiVersion: v1
kind: Secret
metadata:
  name: intake-poller-secret
type: Opaque
stringData:
  GOOGLE_SHEET_ID: <google-sheet-id>
  JOB_QUEUE_URL: https://job-queue-service
  SENDER_EMAIL: ace-model-evals@redhat.com
  AUTO_APPROVE: "false"
  SMTP_HOST: smtp.corp.redhat.com
  SMTP_PORT: "25"
  SMTP_STARTTLS: "false"
  ALLOW_INSECURE_QUEUE_HTTP: "false"
  service-account.json: |-
    <service-account-content>
